name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore LearnAI.sln
      
    - name: Build solution
      run: dotnet build LearnAI.sln --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test LearnAI.sln --configuration Release --no-build --verbosity normal
      
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: |
          **/bin/Release/**
        retention-days: 30